### ISSUE TITLE
XLogWindow的lazy var初始化过早导致windowScene添加不上

### ISSUE THREAD

**Issue by hstdt** [xing3523/XLogConsole#1]
当`XLog`在启动的时候就输出log，导致`XLogWindow`的初始化过早，此时`windowScene`还在`foregroundInactive`状态。

![CleanShot 2022-10-11 at 11 54 17](https://user-images.githubusercontent.com/10215098/194993580-98ca2c69-4449-42c3-9b34-477ff45c1c00.png)

由于`adjustWindowScene()`仅会在`XLogWindow`初始化的时候调用，此后再也无法关联`scene`了，即使调用`show()`。

于是尝试将`adjustWindowScene()`添加到`show()`方法中，此时`XLogWindow`被系统自动设置`isHidden`为`true`，而被`!console.consoleWindow.isHidden`直接return掉。

![CleanShot 2022-10-11 at 11 55 53](https://user-images.githubusercontent.com/10215098/194993729-1be2e495-c113-46ab-b0b0-e48993fd5876.png)

不确定后续方向/思路是去掉`foregroundInactive`判断，还是调整`show()`的逻辑。因此不太好直接提pull request，先提个issue来沟通下

**Comment by xing3523** [comment]
我新建了个工程试了下，是好的，你是在哪个方法里输出的？
 <img width="1115" alt="image" src="https://user-images.githubusercontent.com/11212080/195079236-536f1d56-55d3-42dd-9f4e-0ca5775b34b6.png">

**Comment by xing3523** [comment]
这种场景应该是会进下面通知监听方法设置`windowScene`的，你再确认下？如果是有特殊的场景导致的，方便的话可以发我Demo看看么？

**Comment by hstdt** [comment]
@xing3523 
表层原因，全部的`XLog`被包裹在了`DispatchQueue.main.async`中了。读取状态就会不正常。(原来以为是太早执行了，不对)

Xcode 14.1 beta 3 demo代码如下:

[XLogDemo.zip](https://github.com/xing3523/XLogConsole/files/9755015/XLogDemo.zip)

```swift
DispatchQueue.main.async {
    XLogLevel.debug.log("123")
}
```
为什么这么写，是工程在用SwiftNIO做socket数据传输的时候，非主线程调用`XLog`，会有MainThread Checker警告，并闪退。

**警告**
![CleanShot 2022-10-11 at 20 10 03](https://user-images.githubusercontent.com/10215098/195086200-0193946e-d013-4c9d-8374-fbb59ca61619.png)

<img width="1342" alt="CleanShot 2022-10-11 at 20 14 21" src="https://user-images.githubusercontent.com/10215098/195086735-7db23e25-e97b-4dc6-82c8-1b1e9c92b116.png">

![CleanShot 2022-10-11 at 20 32 58](https://user-images.githubusercontent.com/10215098/195091520-572bc1c0-f222-408d-bce5-559c1baca4c9.png)

这个输出在Out of bounds闪退之后
![CleanShot 2022-10-11 at 20 30 21](https://user-images.githubusercontent.com/10215098/195090829-be4b437a-5d2b-43b4-8f86-91df812a5aea.png)


**Out of bounds闪退**

![CleanShot 2022-10-11 at 20 29 57](https://user-images.githubusercontent.com/10215098/195090751-69ad0699-ed69-4696-a4f2-f36c75db534e.png)

**Comment by xing3523** [comment]
现在看来`windowScene.activationState`的判断有点多余，我给去掉了，异步线程调用也做了兼容，我这边测试没问题，你可以指定develop分支试试，没问题的话我明天再打个tag。

**Comment by hstdt** [comment]
@xing3523 好了，非常感谢~
